# chain.py : Orchestrate the entire RAG process: ingest, store, and search.
# This is the main entry point for the RAG system. It coordinates the data ingestion, vector storage, and retrieval processes. 
# It also provides a simple interface for testing the end-to-end functionality of the RAG system.
# PURPOSE  : Connect retrieved chunks to Phi-3 LLM and get an answer
# USES     : retriever.py (for search), Ollama (for LLM inference)
# CALLED BY: src/app.py (Streamlit UI — next file)

import os
import sys
import time

from src.logger import logger
from src.exception import CustomException
from src.ingestor import DataIngestion
from src.retriever import VectorRetriver

from langchain_ollama import OllamaLLM
from langchain_core.prompts import PromptTemplate
from langchain_core.documents import Document
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

#-- Prompt template for LLM --#
# This prompt template is designed to instruct the LLM on how to use the retrieved chunks of information to answer the user's question. 
# It emphasizes the importance of using only the provided chunks and not making assumptions or using external knowledge. 
# The prompt also encourages the LLM to be concise and to directly address the user's question based on the retrieved information.
# This is what gets sent to Phi-3 for EVERY question
# {context} = the retrieved chunks pasted in automatically
# {question} = the user's question pasted in automatically
PROMPT_TEMPLATE = """
You are a helpful and precise assistant. 
Answer the question using ONLY the information provided in the context below.
If the answer is not in the context, say "I don't have enough information to answer that."
Do NOT make up information.

Context:
{context}

Question: {question}

Answer:

"""

class RAGChain:
    '''
    RAGChain orchestrates the entire Retrieval-Augmented Generation process. 
    It connects the data ingestion, vector storage, and retrieval components to the LLM for answering user questions based on retrieved information.
    
    This is called a "chain" because each step feeds into the next.
    LangChain was built specifically for this pattern.
    
    WHY A CLASS?
    - Encapsulates the entire RAG process in one place
    - Easy to manage state (e.g., ingestor, retriever, LLM instances)
    - Can be extended later with additional methods (e.g., for updating the knowledge base)
    Connects:
      VectorRetriever (finds relevant chunks)
      → PromptTemplate (formats chunks + question)
      → Phi-3 via Ollama (generates answer)
      → StrOutputParser (extracts clean text)
    
    HOW TO USE:
    from src.chain import RAGChain

    rag_chain = RAGChain()
    answer = rag_chain.run("What is the main finding of the report?")
    
    This will return an answer generated by the LLM based on the retrieved chunks of information relevant to the question.
    '''
    def __init__(self, model_name: str = "phi-3"):
        """
        Args:
            model_name : Ollama model to use (default: phi3)
                         Must match exactly what `ollama list` shows
        """
        logger.info(f"Initializing RAGChain with model: {model_name}")
        self.ingestor = DataIngestion()  # Handles PDF loading and chunking
        self.retriever = VectorRetriver()  # Handles vector storage and retrieval
        self.llm = self._load_llm(model_name)  # LLM for generating answers based on retrieved context
        self.prompt = self._build_prompt()
        logger.info("RAGChain initialized successfully. and it's ready to run!")
        
    def _load_llm(self, model_name: str) -> OllamaLLM:
        """
        Load the Ollama LLM with the specified model name.
        
        WHY Ollama?
        - Runs 100% locally on your RTX 3060
        - No API key, no cost, no internet needed
        - Phi-3 at 2.2GB fits comfortably in 6GB VRAM
        - Response time: ~3-8 seconds per answer on your GPU
        Args:
            model_name : Name of the Ollama model to load (e.g., "phi-3")
        Returns:
            An instance of OllamaLLM ready for inference
        
        """
        
        try:
            logger.info(f"Loading Ollama LLM with model: {model_name}")
            
            llm = OllamaLLM(
                model   = model_name,
                temperature = 0.1,  # Lower temperature for more focused answers
                # temperature = 0.1 means:
                #   0.0 = fully deterministic (same answer every time)
                #   1.0 = very creative/random
                #   0.1 = mostly factual with slight flexibility
                #   For RAG over documents: always use 0.0 - 0.2
                )
            
            logger.info(f"Ollama LLM loaded successfully with model: {model_name}")
            return llm
        
        except Exception as e:
            logger.error(f"Failed to load Ollama LLM with model: {model_name}")
            raise CustomException(e, sys)
        
    def _build_prompt(self) -> PromptTemplate:
        """
        Build the prompt template for the LLM.
        PromptTemplate is a string with {placeholders}
        LangChain fills these in automatically when you call the chain.
        This prompt will be used to format the retrieved chunks and the user's question before sending it to the LLM for answer generation.
        Returns:
            A PromptTemplate instance with the defined template
        """
        try:
            
            logger.info("Building prompt template for LLM.")
            prompt = PromptTemplate(
                template        = PROMPT_TEMPLATE,
                input_variables = ["context", "question"]
            )
            logger.info("Prompt template built successfully.") 
            return prompt
        
        except Exception as e:
            logger.error("Failed to build prompt template.")
            raise CustomException(e, sys)
        
    def _format_context(self, results: list[tuple[Document, float]]) -> str:
        """
        Format the retrieved context for the LLM.
        Convert list of (Document, score) tuples into a single string.
        
        WHY FORMAT THIS WAY?
        The LLM reads plain text. We label each chunk with its source
        page so the LLM can say "According to page 2..."
        
        Args:
            context : The retrieved context from the vector store
            results : output from VectorRetriever.search()
        Returns:
            A formatted string ready for LLM input
            Single formatted string with all chunks
        """
        context_parts = []
        
        for i,(doc, score) in enumerate(results):
            page    = doc.metadata.get("page", "unknown?")
            source  = doc.metadata.get("source", "document")
            context_text = doc.page_content.strip().replace("\n", " ")  # Clean up whitespace and newlines
      
            context_parts.append(
                f"Source: {source} | Page: {page} | Relevance: {score:.3f} |\n Content: {context_text}"
                )

        formatted = "\n\n---\n\n".join(context_parts)
        
        logger.info("Formatting retrieved context.")
        return f"Context: {formatted}"
    
    def ask(self, question: str, k: int = 5) -> dict:
        """
        Main method to run the RAG chain  — ask a question and get an answer.
        Takes a user question, retrieves relevant chunks, formats the prompt, and gets an answer from the LLM.
        
        Full pipeline:
          1. Search ChromaDB for top-k relevant chunks
          2. Format chunks into context string
          3. Fill prompt template with context + question
          4. Send to Phi-3 → get answer
          5. Return answer + source chunks (for transparency)
          
        Args:
            question : The user's question as plain string to be answered   
            results  : The retrieved chunks from the vector store (list of (Document, score) tuples)
            k        : Number of top chunks to include in the context (default: 5)
                
        Returns:
            A dictionary containing the answer and any additional information.
            dict with keys:
              "answer"   : Phi-3's answer as a string
              "sources"  : list of source chunks used
              "duration" : total time in seconds
        
        """
        
        try:
            logger.info(f"Running RAG chain for question: {question}")
            start = time.time()
            
            # Step 1: Format the retrieved context for the LLM
            results = self.retriever.search(question, k)  # Take top-k results
        
            # Step 2: Fill the prompt template with the formatted context and the user's question
            context = self._format_context(results)
            logger.info(f"Context built from {len(results)} chunks")  # Log how many chunks are being sent to the LLM for transparency
            
            # Step 3: build full prompt with context + question
            filled_prompt = self.prompt.format(
                context=context, 
                question=question
                )
            
            # Step 4: Send the prompt to the LLM and get the answer
            logger.info("Sending prompt to Phi-3 via Ollama...")
            answer = self.llm.invoke(filled_prompt)
            
            duration = round(time.time() - start, 2)
            logger.info(f"RAG chain completed in {duration} seconds.")
            logger.info(f"Answer preview: {str(answer)[:100]}...")
            
            # Step 5: Return the answer along with the source chunks for transparency 
            return {
                "answer": answer.strip(),  # Clean up whitespace
                "sources": results,  # Include source chunks for transparency
                "duration": duration
            }
            
        except Exception as e:
            logger.error("Error during RAG chain execution.")
            raise CustomException(e, sys)
        
        
# ── Run directly to test ───────────────────────────────────────────────────
if __name__ == "__main__":

    # Test questions for the hotel daily report
    test_questions = [
        "What is the total room revenue?",
        "What is the occupancy rate?",
        "How many rooms were sold today?",
    ]

    try:
        chain = RAGChain(model_name="phi3")

        for question in test_questions:
            print("\n" + "="*60)
            print(f"Question : {question}")
            print("="*60)

            response = chain.ask(question, k=3)

            print(f"Answer   : {response['answer']}")
            print(f"Duration : {response['duration']}s")
            print(f"Sources  : {len(response['sources'])} chunks used")

            # Show which pages were used
            for i, (doc, score) in enumerate(response["sources"]):
                page = doc.metadata.get("page", "?")
                print(f"  [{i+1}] Page {page} | Score {score:.4f}")

    except CustomException as e:
        print(f"\nERROR: {e}\n")